server:
  port: 18081
#必须加上这句active，不然yml文件不会被加载
spring:
  profiles:
    active: dev
  hsf:
    pi:
      version: 1.0.0
      timeout: 3000
      serviceGroup: yingzi-dev
  application:
    name: pi-provider

kafka:
  internal:
    bootstrap-servers: 172.19.60.201:9092
    producer:
      retries: 0
      batch-size: 10
      buffer-memory: 5120000
    consumer:
      group-id: pi-internal-group
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
  external:
    bootstrap-servers: 172.19.60.201:9093
    producer:
      retries: 0
      batch-size: 10
      buffer-memory: 5120000
    consumer:
      group-id: pi-external-group
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yingzi.center.pi.model,com.yingzi.center.pi.model.*

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

yz:
  logging:
    id: yingzi-center-iot
    package: com.yingzi.center.pi
    desc: